version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.2
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external
